band_name: Kali Yuga
genre: Death Metal
domain: kali-yuga.de
location: 07549 Gera
keywords:
  - Kali Yuga
  - Kaliyuga
  - Kali-Yuga
  - Death Metal
  - Melodic Death Metal
  - Band
  - Gera

description:
  feed: Die offizielle Homepage der Geraer Death Metal Band KALI YUGA mit Infos zu Merchandise, Live Shows und vielem mehr.
  releases: Die offizielle Homepage der Geraer Death Metal Band KALI YUGA mit Infos zu Merchandise, Live Shows und vielem mehr.
  lineup: Die Geraer Death Metal Band KALI YUGA SCOPE besteht aus Michael (Gitarre), Eik (Gitarre), Christian (Gesang), Jan (Bass) und Jean-Peer (Schlagzeug).
  shows: Die offizielle Homepage der Geraer Death Metal Band KALI YUGA mit Infos zu Merchandise, Live Shows und vielem mehr.
  gallery: Die offizielle Homepage der Geraer Death Metal Band KALI YUGA mit Infos zu Merchandise, Live Shows und vielem mehr.
  merch: Die offizielle Homepage der Geraer Death Metal Band KALI YUGA mit Infos zu Merchandise, Live Shows und vielem mehr.
  impressum: kontakt@kali-yuga.de
  contact: kontakt@kali-yuga.de

contact:
  - title: Management & Booking
    name: Eik Halle, Michael Albert
    email: booking@kali-yuga.de
  - title: Merchandise
    name: Jean-Peer Krutz
    email: merch@kali-yuga.de
  - title: Allgemeiner Kontakt
    name: Jan Koch
    email: kontakt@kali-yuga.de
  - title: Homepage
    name: Christian Glöckner
    email: webmaster@kali-yuga.de

imprint:
  represented_by:
    - Jan Koch
    - c/o Rechtsanwälte Diehl & Pape
    - Innere Plauensche Straße 20
    - 08056 Zwickau
  phone: 0365-2041114

profiles:
  facebook: https://www.facebook.com/kaliyugametal
  instagram: https://www.instagram.com/kaliyugametal
  youtube: https://www.youtube.com/@KaliYugametal1
  spotify: https://open.spotify.com/intl-de/artist/0DhRXdfjAaiKLTZ2vYYbtI?si=-2ces9spQZi5ic2azTuAFw
  # soundcloud: https://soundcloud.com/eik-halle

navigation:
  - releases
  - lineup
  - shows
  - gallery
  - merch
